name: Kingdom
version: 1.0.0
main: KingdomPlugin
api-version: 1.21
author: KingdomCraft
description: Kingdom commands plugin
commands:
  kingdom:
    description: Kingdom commands
    usage: /kingdom
  coins:
    description: Check coins
    usage: /coins
